### ISSUE TITLE
Media files that other files than audio files

### ISSUE THREAD

**Issue by obadx** [obadx/prepare-quran-dataset#24]
* url: https://zekr.online/ar/author/35/hmd-aas-lmaasro/quran?mushaf_id=10341
```python
Traceback (most recent call last):
  File "/lfs01/workdirs/shams035u1/codes/prepare-quran-dataset/frontend/utils.py", line 313, in download_all_moshaf_task
    moshaf_pool.download_moshaf(
  File "/lfs01/workdirs/shams035u1/codes/prepare-quran-dataset/src/prepare_quran_dataset/construct/database.py", line 177, in download_moshaf
    moshaf = download_media_and_fill_metadata(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lfs01/workdirs/shams035u1/codes/prepare-quran-dataset/src/prepare_quran_dataset/construct/database.py", line 257, in download_media_and_fill_metadata
    item.fill_metadata_after_download(moshaf_path=moshaf_path)
  File "/lfs01/workdirs/shams035u1/codes/prepare-quran-dataset/src/prepare_quran_dataset/construct/data_classes.py", line 498, in fill_metadata_after_download
    audio_file_info = get_audiofile_info(filepath)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lfs01/workdirs/shams035u1/codes/prepare-quran-dataset/src/prepare_quran_dataset/construct/utils.py", line 207, in get_audiofile_info
    audio = File(audiofile_path)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/shams035u1/data/miniconda3/envs/prepare-ds/lib/python3.12/site-packages/mutagen/_util.py", line 164, in wrapper_func
    return func(h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shams035u1/data/miniconda3/envs/prepare-ds/lib/python3.12/site-packages/mutagen/_file.py", line 302, in File
    return Kind(fileobj, filename=filething.filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shams035u1/data/miniconda3/envs/prepare-ds/lib/python3.12/site-packages/mutagen/_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "/home/shams035u1/data/miniconda3/envs/prepare-ds/lib/python3.12/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shams035u1/data/miniconda3/envs/prepare-ds/lib/python3.12/site-packages/mutagen/id3/_file.py", line 420, in load
    self.info = self._Info(fileobj, offset)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shams035u1/data/miniconda3/envs/prepare-ds/lib/python3.12/site-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shams035u1/data/miniconda3/envs/prepare-ds/lib/python3.12/site-packages/mutagen/mp3/__init__.py", line 401, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame
```

**Comment by obadx** [comment]
I think the origin of the error from `zekr` extact function

**Comment by obadx** [comment]
* create generic file reader
* rename media files with its true media type

**Comment by obadx** [comment]
The error in the `deduce_filename` function fails to read the file name form the url [url](https://cdns1.zekr.online/quran/10341/1/128.mp3)
